import bcrypt from "bcryptjs";

const data = {
    users: [{
            name: "Andrei",
            email: "admin@ase.ro",
            password: bcrypt.hashSync("1234", 8),
            isAdmin: true,
        },
        {
            name: "John",
            email: "user@ase.ro",
            password: bcrypt.hashSync("1234", 8),
            isAdmin: false,
        }
    ],
    products: [{
            name: 'IT Stephen King',
            category: 'book',
            image: '/images/produs-1.jpg',
            price: 80,
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name: 'Pet Sematary Stephen King',
            category: 'book',
            image: '/images/produs-8.jpg',
            price: 85,
            countInStock: 10,
            rating: 5,
            numReviews: 12,
            description: 'High quality product',
        },
        {
            name: 'Ice & Fire George R.R. Martin',
            category: 'book',
            image: '/images/produs-7.jpg',
            price: 83,
            countInStock: 10,
            rating: 3.5,
            numReviews: 7,
            description: 'High quality product',
        },
        {
            name: 'To Kill A Mockingbird Harper Lee',
            category: 'book',
            image: '/images/produs-9.jpg',
            price: 44.99,
            countInStock: 10,
            rating: 4.5,
            numReviews: 20,
            description: 'High quality product',
        },
        {
            name: '1984 George Orwell',
            category: 'book',
            image: '/images/produs-10.jpeg',
            price: 88,
            countInStock: 10,
            rating: 4,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name: 'Animal Farm George Orwell',
            category: 'book',
            image: '/images/produs-11.jpg',
            price: 22.5,
            countInStock: 10,
            rating: 3.5,
            numReviews: 20,
            description: 'High quality product',
        },
        {
            name: 'Laptop DELL',
            category: 'pc',
            image: '/images/produs-2.jpg',
            price: 299.99,
            countInStock: 10,
            rating: 4.5,
            numReviews: 120,
            description: 'High quality product',
        },
        {
            name: 'Bicicleta Pegas Albastra',
            category: 'bike',
            image: '/images/produs-3.jpg',
            price: 110,
            countInStock: 10,
            rating: 3,
            numReviews: 14,
            description: 'High quality product',
        },
        {
            name: 'Smartphone A909',
            category: 'phone',
            image: '/images/produs-4.jpg',
            price: 269.99,
            countInStock: 10,
            rating: 4,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name: 'Volvo XC90',
            category: 'car',
            image: '/images/produs-5.jpg',
            price: 35000,
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name: 'Joc video GTA VI',
            category: 'game',
            image: '/images/produs-6.jpg',
            price: 149.99,
            countInStock: 0,
            rating: 4.5,
            numReviews: 110,
            description: 'High quality product',
        }
    ]
};

export default data;